name: Chache Testing

on:
  push:
    branches: ["main"]
  pull:
    branches: ["main"]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Perform Tests
      run: make test

  build:

    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: make build
